import { describe, expect, it } from "vitest";
import { parseGitAttributes } from "../src/config/load.js";
import {
  classifyRole,
  emptyRoleAttributes,
  emptyRolePatterns,
  matchesAny,
  type RoleAttributes,
  type RolePatterns,
} from "../src/core/files/roles.js";

function classify(
  path: string,
  head = "",
  patterns: Partial<RolePatterns> = {},
  attributes: Partial<RoleAttributes> = {},
) {
  return classifyRole(
    path,
    head,
    { ...emptyRolePatterns(), ...patterns },
    { ...emptyRoleAttributes(), ...attributes },
  );
}

describe("matchesAny", () => {
  it("returns false for an empty pattern list", () => {
    expect(matchesAny("src/a.ts", [])).toBe(false);
  });

  it("matches on the full path or the basename", () => {
    expect(matchesAny("src/deep/a.min.js", ["**/deep/**"])).toBe(true);
    expect(matchesAny("src/deep/a.min.js", ["*.min.js"])).toBe(true);
    expect(matchesAny("src/a.ts", ["*.py"])).toBe(false);
  });
});

describe("classifyRole", () => {
  it("defaults to source", () => {
    expect(classify("src/index.ts")).toBe("source");
  });

  it("detects tests by directory and by filename", () => {
    expect(classify("src/__tests__/a.js")).toBe("test");
    expect(classify("test/a.js")).toBe("test");
    expect(classify("spec/a.js")).toBe("test");
    expect(classify("src/a.test.ts")).toBe("test");
    expect(classify("src/a-spec.js")).toBe("test");
    expect(classify("fixtures/a.js")).toBe("test");
    expect(classify("scripts/benchmarks/a.js")).toBe("test");
  });

  it("detects vendored directories", () => {
    expect(classify("vendor/lib.js")).toBe("vendored");
    expect(classify("third_party/lib.js")).toBe("vendored");
    expect(classify("flow-typed/react.js")).toBe("vendored");
  });

  it("detects generated files by name", () => {
    expect(classify("dist/app.min.js")).toBe("generated");
    expect(classify("src/schema.generated.ts")).toBe("generated");
    expect(classify("api/service.pb.go")).toBe("generated");
  });

  it("detects generated files by header", () => {
    expect(classify("src/schema.ts", "// @generated by protoc\n")).toBe("generated");
    expect(classify("src/a.go", "// Code generated by mockgen. DO NOT EDIT.\n")).toBe("generated");
    expect(classify("src/a.ts", "const a = 1;\n")).toBe("source");
  });

  it("detects docs by extension and directory", () => {
    expect(classify("README.md")).toBe("docs");
    expect(classify("NOTES.txt")).toBe("docs");
    expect(classify("docs/guide.html")).toBe("docs");
  });

  it("lets .gitattributes override path heuristics", () => {
    expect(classify("src/api.ts", "", {}, { generated: ["src/api.ts"] })).toBe("generated");
    expect(classify("src/lib.ts", "", {}, { vendored: ["src/**"] })).toBe("vendored");
    expect(classify("src/page.ts", "", {}, { docs: ["src/page.ts"] })).toBe("docs");
  });

  it("lets config patterns override everything", () => {
    expect(classify("src/__tests__/real.ts", "", { source: ["src/__tests__/**"] })).toBe("source");
    expect(classify("src/app.ts", "@generated", { source: ["src/app.ts"] })).toBe("source");
    expect(classify("e2e/flow.ts", "", { test: ["e2e/**"] })).toBe("test");
  });
});

describe("parseGitAttributes", () => {
  it("returns empty buckets for empty input", () => {
    expect(parseGitAttributes("")).toEqual({ generated: [], vendored: [], docs: [] });
  });

  it("collects linguist markers", () => {
    const result = parseGitAttributes(
      [
        "# a comment",
        "",
        "dist/** linguist-generated=true",
        "vendor/** linguist-vendored",
        "*.md linguist-documentation=true",
      ].join("\n"),
    );

    expect(result.generated).toEqual(["dist/**"]);
    expect(result.vendored).toEqual(["vendor/**"]);
    expect(result.docs).toEqual(["*.md"]);
  });

  it("ignores negated and false markers, and unrelated attributes", () => {
    const result = parseGitAttributes(
      ["a/** -linguist-generated", "b/** linguist-generated=false", "c/** text eol=lf"].join("\n"),
    );

    expect(result).toEqual({ generated: [], vendored: [], docs: [] });
  });

  it("normalizes leading slashes and trailing directory markers", () => {
    expect(parseGitAttributes("/build/ linguist-generated").generated).toEqual(["build/**"]);
  });
});
