import path from "node:path";
import { globToRegExp, toPosix } from "./matcher.js";

export type FileRole = "source" | "test" | "generated" | "vendored" | "docs";

export const FILE_ROLES: FileRole[] = ["source", "test", "generated", "vendored", "docs"];

export type RolePatterns = Record<FileRole, string[]>;

export interface RoleAttributes {
  generated: string[];
  vendored: string[];
  docs: string[];
}

export const HEAD_BYTES = 2048;

const GENERATED_HEADER =
  /@generated|code generated by|do not edit|autogenerated|auto-generated|generated by/i;

const TEST_DIRS = new Set([
  "__tests__",
  "__mocks__",
  "__fixtures__",
  "__snapshots__",
  "test",
  "tests",
  "spec",
  "specs",
  "e2e",
  "fixtures",
  "benchmarks",
]);

const VENDOR_DIRS = new Set([
  "vendor",
  "vendored",
  "third_party",
  "third-party",
  "flow-typed",
  "node_modules",
  "bower_components",
]);

const DOC_DIRS = new Set(["docs", "doc"]);

const DOC_EXTENSIONS = new Set([".md", ".markdown", ".txt", ".rst", ".adoc"]);

const TEST_FILE = /[.\-_](test|spec)\.[^.]+$/i;

const GENERATED_FILE = /\.(min|bundle|generated)\.[^.]+$|(^|[.\-_])pb\.[^.]+$/i;

export function matchesAny(relativePath: string, globs: string[]): boolean {
  if (globs.length === 0) {
    return false;
  }
  const posixPath = toPosix(relativePath);
  const base = posixPath.slice(posixPath.lastIndexOf("/") + 1);
  return globs.some((glob) => {
    const re = globToRegExp(glob);
    return re.test(posixPath) || re.test(base);
  });
}

function fromPatterns(relativePath: string, patterns: RolePatterns): FileRole | undefined {
  return FILE_ROLES.find((role) => matchesAny(relativePath, patterns[role]));
}

function fromAttributes(relativePath: string, attributes: RoleAttributes): FileRole | undefined {
  if (matchesAny(relativePath, attributes.generated)) {
    return "generated";
  }
  if (matchesAny(relativePath, attributes.vendored)) {
    return "vendored";
  }
  return matchesAny(relativePath, attributes.docs) ? "docs" : undefined;
}

function fromPath(relativePath: string): FileRole | undefined {
  const posixPath = toPosix(relativePath);
  const segments = posixPath.split("/");
  const base = segments[segments.length - 1] as string;
  const dirs = segments.slice(0, -1);

  if (dirs.some((dir) => VENDOR_DIRS.has(dir))) {
    return "vendored";
  }
  if (GENERATED_FILE.test(base)) {
    return "generated";
  }
  if (dirs.some((dir) => TEST_DIRS.has(dir)) || TEST_FILE.test(base)) {
    return "test";
  }
  if (
    dirs.some((dir) => DOC_DIRS.has(dir)) ||
    DOC_EXTENSIONS.has(path.extname(base).toLowerCase())
  ) {
    return "docs";
  }
  return undefined;
}

export function classifyRole(
  relativePath: string,
  head: string,
  patterns: RolePatterns,
  attributes: RoleAttributes,
): FileRole {
  return (
    fromPatterns(relativePath, patterns) ??
    fromAttributes(relativePath, attributes) ??
    (GENERATED_HEADER.test(head) ? "generated" : undefined) ??
    fromPath(relativePath) ??
    "source"
  );
}

export function emptyRolePatterns(): RolePatterns {
  return { source: [], test: [], generated: [], vendored: [], docs: [] };
}

export function emptyRoleAttributes(): RoleAttributes {
  return { generated: [], vendored: [], docs: [] };
}
